### ISSUE TITLE
For PHP 7.3 Not work PHP-FPM!

### ISSUE THREAD

**Issue by itgopher** [thamaraiselvam/LEMP-Installer#14]
Please in nginx.conf - set php7-fpm.sock, but need set php7.3-fpm.sock

**Comment by thamaraiselvam** [comment]
I am thinking of installing just `php-fpm`. It will take care of the latest version. what do you think?

**Comment by thamaraiselvam** [comment]
Anybody want to grab this?

**Comment by marksitko** [comment]
I tested it out and it seems that the correct php-fpm sock version is set but there are some other problems with nginx. I grab it and fix issues is will be discover

**Comment by thamaraiselvam** [comment]
great @marksitko . I have assigned you to this issue
