### ISSUE TITLE
Support for Arch Linux

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/LEMP-Installer#2]
Now the script supports only on Debian based distributions. We need to add support for other distributions as well.

Initially, let's start with Arch Linux

First, write a method to find distribution, Then create a new method and call it whenever current operating system is Arch Linux.

This part should be generic so when new distribution comes in we can add it easily

**Comment by alexandersperling** [comment]
Hi, if you want you can assign me and I would take this over.
As a first step I could imagine to integrate the method to find the distribution.

**Comment by thamaraiselvam** [comment]
PR https://github.com/thamaraiselvam/LEMP-Installer/pull/9 Merged

**Comment by thamaraiselvam** [comment]
Really appreciate your interest @alexandersperling This one is already merged PR https://github.com/thamaraiselvam/LEMP-Installer/pull/9

I have set the base to support all operating system, Still, if you want to contribute, please  do it for Issue https://github.com/thamaraiselvam/LEMP-Installer/issues/7 (Mac support)

**Comment by alexandersperling** [comment]
Hi @thamaraiselvam unfortunately I don't work on a mac so I'm not quite sure how it will be done there. However, I will look into it. 
Additionally I have a small suggestion, to include shellcheck as build job to keep a good standard for shell scripts. I would create an issue for this and raise a PR if you are fine.
