### ISSUE TITLE
Add Travis CI 

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/LEMP-Installer#4]

**Comment by 73VW** [comment]
Hey! I can work on this. What do you really want to do with Travis CI?

**Comment by thamaraiselvam** [comment]
Oops. I missed your message and working on it. I just wanted that script should execute without errors.

**Comment by thamaraiselvam** [comment]
PR https://github.com/thamaraiselvam/LEMP-Installer/pull/6 Merged
